// Generated by gencpp from file ros_dnn_msgs/DetectFeedback.msg
// DO NOT EDIT!


#ifndef ROS_DNN_MSGS_MESSAGE_DETECTFEEDBACK_H
#define ROS_DNN_MSGS_MESSAGE_DETECTFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_dnn_msgs
{
template <class ContainerAllocator>
struct DetectFeedback_
{
  typedef DetectFeedback_<ContainerAllocator> Type;

  DetectFeedback_()
    {
    }
  DetectFeedback_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::ros_dnn_msgs::DetectFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_dnn_msgs::DetectFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct DetectFeedback_

typedef ::ros_dnn_msgs::DetectFeedback_<std::allocator<void> > DetectFeedback;

typedef boost::shared_ptr< ::ros_dnn_msgs::DetectFeedback > DetectFeedbackPtr;
typedef boost::shared_ptr< ::ros_dnn_msgs::DetectFeedback const> DetectFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_dnn_msgs::DetectFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_dnn_msgs::DetectFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ros_dnn_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/lunar/share/std_msgs/cmake/../msg'], 'ros_dnn_msgs': ['/home/nvidia/catkin_ws/src/ros_dnn/ros_dnn_msgs/msg', '/home/nvidia/catkin_ws/devel/share/ros_dnn_msgs/msg'], 'geometry_msgs': ['/opt/ros/lunar/share/geometry_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/lunar/share/sensor_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/lunar/share/actionlib_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ros_dnn_msgs::DetectFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_dnn_msgs::DetectFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_dnn_msgs::DetectFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_dnn_msgs::DetectFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_dnn_msgs::DetectFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_dnn_msgs::DetectFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_dnn_msgs::DetectFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::ros_dnn_msgs::DetectFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_dnn_msgs::DetectFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_dnn_msgs/DetectFeedback";
  }

  static const char* value(const ::ros_dnn_msgs::DetectFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_dnn_msgs::DetectFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# Feedback\n\
\n\
";
  }

  static const char* value(const ::ros_dnn_msgs::DetectFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_dnn_msgs::DetectFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DetectFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_dnn_msgs::DetectFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::ros_dnn_msgs::DetectFeedback_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // ROS_DNN_MSGS_MESSAGE_DETECTFEEDBACK_H
