; Auto-generated. Do not edit!


(cl:in-package ros_dnn_msgs-msg)


;//! \htmlinclude DetectFeedback.msg.html

(cl:defclass <DetectFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass DetectFeedback (<DetectFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <DetectFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'DetectFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name ros_dnn_msgs-msg:<DetectFeedback> is deprecated: use ros_dnn_msgs-msg:DetectFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <DetectFeedback>) ostream)
  "Serializes a message object of type '<DetectFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <DetectFeedback>) istream)
  "Deserializes a message object of type '<DetectFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<DetectFeedback>)))
  "Returns string type for a message object of type '<DetectFeedback>"
  "ros_dnn_msgs/DetectFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'DetectFeedback)))
  "Returns string type for a message object of type 'DetectFeedback"
  "ros_dnn_msgs/DetectFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<DetectFeedback>)))
  "Returns md5sum for a message object of type '<DetectFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'DetectFeedback)))
  "Returns md5sum for a message object of type 'DetectFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<DetectFeedback>)))
  "Returns full string definition for message of type '<DetectFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Feedback~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'DetectFeedback)))
  "Returns full string definition for message of type 'DetectFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Feedback~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <DetectFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <DetectFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'DetectFeedback
))
