(cl:defpackage ros_dnn_msgs-msg
  (:use )
  (:export
   "<DETECTACTION>"
   "DETECTACTION"
   "<DETECTACTIONFEEDBACK>"
   "DETECTACTIONFEEDBACK"
   "<DETECTACTIONGOAL>"
   "DETECTACTIONGOAL"
   "<DETECTACTIONRESULT>"
   "DETECTACTIONRESULT"
   "<DETECTFEEDBACK>"
   "DETECTFEEDBACK"
   "<DETECTGOAL>"
   "DETECTGOAL"
   "<DETECTRESULT>"
   "DETECTRESULT"
   "<PREDICTION>"
   "PREDICTION"
   "<PREDICTIONS>"
   "PREDICTIONS"
  ))

